### ISSUE TITLE
StockBugFix: Great Hall Bonus issue

### ISSUE THREAD

**Issue by PsychoDad9999** [peterhaneve/ONIMods#226]
## Current Behavior
With StockBugFix-Mod enabled, all of my great halls are downgraded to mess halls. After loading a savegame the great hall is visible for a second and than changed to a mess hall.

When a mess table is constructed or deconstructed the Great Hall Bonus is applied again, but I have to repeat this every time after loading a savegame. 

I don't see this issue, when StockBugFix Mod is disabled.

## Mod Versions
GameVersion U41 498381-5
Mod Version 3.13.0.0

![messhall](https://user-images.githubusercontent.com/52836134/167667437-5c4c56cd-58d0-4773-a126-31bf90cd607b.jpg)
[Player.log](https://github.com/peterhaneve/ONIMods/files/8662990/Player.log)

**Comment by peterhaneve** [comment]
All attempts to reproduce this issue have failed. It may be specific to your machine.

I have pushed a special hotfix for the current stable branch to try and fix the issue, but with no way to reproduce it I have no idea if it will actually help.

**Comment by PsychoDad9999** [comment]
Thanks for trying to fix the issue. I've updated StockBugFix but unfortunately the issue is not fixed. 

I've disabled all mods except Modupdater and StockBugFix, started a new sandbox game and can reproduce the issue immediately. Will it help if I share my savegame?

**Comment by peterhaneve** [comment]
I finally managed to reproduce this one, by running on very slow speed with adding the buildings and plants in a specific order. The issue should be actually fixed in 3.13.6.0 (Stable) / 3.16.0.0 (Public Testing).

**Comment by PsychoDad9999** [comment]
Awesome, thank you.
